// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module my_prj_decision_function_ap_fixed_18_8_5_3_0_ap_fixed_18_8_5_3_0_13 (
        ap_clk,
        ap_rst,
        x_0_val,
        x_1_val,
        x_2_val,
        x_3_val,
        x_5_val,
        x_6_val,
        x_8_val,
        x_9_val,
        ap_return,
        ap_ce
);


input   ap_clk;
input   ap_rst;
input  [17:0] x_0_val;
input  [17:0] x_1_val;
input  [17:0] x_2_val;
input  [17:0] x_3_val;
input  [17:0] x_5_val;
input  [17:0] x_6_val;
input  [17:0] x_8_val;
input  [17:0] x_9_val;
output  [10:0] ap_return;
input   ap_ce;

reg[10:0] ap_return;

wire   [0:0] icmp_ln4_fu_186_p2;
reg   [0:0] icmp_ln4_reg_659;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln4_reg_659_pp0_iter1_reg;
reg   [0:0] icmp_ln4_reg_659_pp0_iter2_reg;
wire   [0:0] icmp_ln4_130_fu_192_p2;
reg   [0:0] icmp_ln4_130_reg_670;
wire   [0:0] icmp_ln4_131_fu_198_p2;
reg   [0:0] icmp_ln4_131_reg_676;
wire   [0:0] icmp_ln4_132_fu_204_p2;
reg   [0:0] icmp_ln4_132_reg_682;
wire   [0:0] icmp_ln4_133_fu_210_p2;
reg   [0:0] icmp_ln4_133_reg_688;
reg   [0:0] icmp_ln4_133_reg_688_pp0_iter1_reg;
wire   [0:0] icmp_ln4_134_fu_216_p2;
reg   [0:0] icmp_ln4_134_reg_694;
reg   [0:0] icmp_ln4_134_reg_694_pp0_iter1_reg;
reg   [0:0] icmp_ln4_134_reg_694_pp0_iter2_reg;
wire   [0:0] icmp_ln4_135_fu_222_p2;
reg   [0:0] icmp_ln4_135_reg_700;
reg   [0:0] icmp_ln4_135_reg_700_pp0_iter1_reg;
reg   [0:0] icmp_ln4_135_reg_700_pp0_iter2_reg;
reg   [0:0] icmp_ln4_135_reg_700_pp0_iter3_reg;
wire   [0:0] icmp_ln4_136_fu_228_p2;
reg   [0:0] icmp_ln4_136_reg_706;
reg   [0:0] icmp_ln4_136_reg_706_pp0_iter1_reg;
wire   [0:0] icmp_ln4_137_fu_234_p2;
reg   [0:0] icmp_ln4_137_reg_711;
wire   [0:0] icmp_ln4_138_fu_240_p2;
reg   [0:0] icmp_ln4_138_reg_716;
reg   [0:0] icmp_ln4_138_reg_716_pp0_iter1_reg;
wire   [0:0] icmp_ln4_139_fu_246_p2;
reg   [0:0] icmp_ln4_139_reg_721;
reg   [0:0] icmp_ln4_139_reg_721_pp0_iter1_reg;
wire   [0:0] icmp_ln4_140_fu_252_p2;
reg   [0:0] icmp_ln4_140_reg_726;
reg   [0:0] icmp_ln4_140_reg_726_pp0_iter1_reg;
reg   [0:0] icmp_ln4_140_reg_726_pp0_iter2_reg;
wire   [0:0] icmp_ln4_141_fu_258_p2;
reg   [0:0] icmp_ln4_141_reg_731;
reg   [0:0] icmp_ln4_141_reg_731_pp0_iter1_reg;
reg   [0:0] icmp_ln4_141_reg_731_pp0_iter2_reg;
wire   [0:0] icmp_ln4_142_fu_264_p2;
reg   [0:0] icmp_ln4_142_reg_736;
reg   [0:0] icmp_ln4_142_reg_736_pp0_iter1_reg;
reg   [0:0] icmp_ln4_142_reg_736_pp0_iter2_reg;
wire   [0:0] icmp_ln4_143_fu_270_p2;
reg   [0:0] icmp_ln4_143_reg_741;
reg   [0:0] icmp_ln4_143_reg_741_pp0_iter1_reg;
reg   [0:0] icmp_ln4_143_reg_741_pp0_iter2_reg;
reg   [0:0] icmp_ln4_143_reg_741_pp0_iter3_reg;
wire   [0:0] and_ln105_fu_281_p2;
reg   [0:0] and_ln105_reg_746;
wire   [0:0] and_ln107_fu_290_p2;
reg   [0:0] and_ln107_reg_753;
wire   [0:0] and_ln105_142_fu_295_p2;
reg   [0:0] and_ln105_142_reg_758;
reg   [0:0] and_ln105_142_reg_758_pp0_iter2_reg;
wire   [0:0] and_ln107_15_fu_305_p2;
reg   [0:0] and_ln107_15_reg_765;
reg   [0:0] and_ln107_15_reg_765_pp0_iter2_reg;
reg   [0:0] and_ln107_15_reg_765_pp0_iter3_reg;
wire   [0:0] and_ln105_143_fu_311_p2;
reg   [0:0] and_ln105_143_reg_771;
wire   [0:0] and_ln105_144_fu_321_p2;
reg   [0:0] and_ln105_144_reg_777;
wire   [0:0] or_ln120_fu_337_p2;
reg   [0:0] or_ln120_reg_783;
wire   [0:0] and_ln105_145_fu_348_p2;
reg   [0:0] and_ln105_145_reg_788;
wire   [0:0] or_ln120_110_fu_385_p2;
reg   [0:0] or_ln120_110_reg_793;
wire   [3:0] select_ln120_128_fu_453_p3;
reg   [3:0] select_ln120_128_reg_799;
wire   [0:0] or_ln120_114_fu_508_p2;
reg   [0:0] or_ln120_114_reg_804;
wire   [3:0] select_ln120_134_fu_552_p3;
reg   [3:0] select_ln120_134_reg_809;
wire    ap_block_pp0_stage0;
wire   [0:0] xor_ln107_59_fu_285_p2;
wire   [0:0] xor_ln107_fu_276_p2;
wire   [0:0] xor_ln107_60_fu_300_p2;
wire   [0:0] xor_ln107_61_fu_316_p2;
wire   [0:0] and_ln105_155_fu_326_p2;
wire   [0:0] and_ln105_148_fu_331_p2;
wire   [0:0] xor_ln107_62_fu_343_p2;
wire   [0:0] and_ln105_156_fu_360_p2;
wire   [0:0] and_ln105_149_fu_356_p2;
wire   [0:0] or_ln120_107_fu_375_p2;
wire   [0:0] and_ln105_150_fu_365_p2;
wire   [0:0] and_ln105_147_fu_352_p2;
wire   [0:0] xor_ln120_fu_390_p2;
wire   [1:0] zext_ln120_fu_396_p1;
wire   [1:0] select_ln120_fu_400_p3;
wire   [1:0] select_ln120_123_fu_407_p3;
wire   [2:0] zext_ln120_21_fu_414_p1;
wire   [0:0] or_ln120_106_fu_370_p2;
wire   [2:0] select_ln120_124_fu_418_p3;
wire   [2:0] select_ln120_125_fu_425_p3;
wire   [0:0] or_ln120_108_fu_379_p2;
wire   [2:0] select_ln120_126_fu_433_p3;
wire   [2:0] select_ln120_127_fu_441_p3;
wire   [3:0] zext_ln120_22_fu_449_p1;
wire   [0:0] xor_ln107_63_fu_460_p2;
wire   [0:0] and_ln105_157_fu_473_p2;
wire   [0:0] and_ln105_146_fu_465_p2;
wire   [0:0] and_ln105_151_fu_469_p2;
wire   [0:0] and_ln105_152_fu_478_p2;
wire   [0:0] or_ln120_112_fu_498_p2;
wire   [0:0] and_ln105_153_fu_483_p2;
wire   [0:0] or_ln120_109_fu_488_p2;
wire   [3:0] select_ln120_129_fu_514_p3;
wire   [0:0] or_ln120_111_fu_493_p2;
wire   [3:0] select_ln120_130_fu_521_p3;
wire   [3:0] select_ln120_131_fu_528_p3;
wire   [0:0] or_ln120_113_fu_502_p2;
wire   [3:0] select_ln120_132_fu_536_p3;
wire   [3:0] select_ln120_133_fu_544_p3;
wire   [0:0] xor_ln107_64_fu_560_p2;
wire   [0:0] and_ln105_158_fu_565_p2;
wire   [0:0] and_ln105_154_fu_570_p2;
wire   [0:0] or_ln120_115_fu_575_p2;
wire   [10:0] agg_result_fu_587_p33;
wire   [3:0] agg_result_fu_587_p34;
wire   [10:0] agg_result_fu_587_p35;
reg    ap_ce_reg;
reg   [17:0] x_0_val_int_reg;
reg   [17:0] x_1_val_int_reg;
reg   [17:0] x_2_val_int_reg;
reg   [17:0] x_3_val_int_reg;
reg   [17:0] x_5_val_int_reg;
reg   [17:0] x_6_val_int_reg;
reg   [17:0] x_8_val_int_reg;
reg   [17:0] x_9_val_int_reg;
reg   [10:0] ap_return_int_reg;
wire   [3:0] agg_result_fu_587_p1;
wire   [3:0] agg_result_fu_587_p3;
wire   [3:0] agg_result_fu_587_p5;
wire   [3:0] agg_result_fu_587_p7;
wire   [3:0] agg_result_fu_587_p9;
wire   [3:0] agg_result_fu_587_p11;
wire   [3:0] agg_result_fu_587_p13;
wire   [3:0] agg_result_fu_587_p15;
wire  signed [3:0] agg_result_fu_587_p17;
wire  signed [3:0] agg_result_fu_587_p19;
wire  signed [3:0] agg_result_fu_587_p21;
wire  signed [3:0] agg_result_fu_587_p23;
wire  signed [3:0] agg_result_fu_587_p25;
wire  signed [3:0] agg_result_fu_587_p27;
wire  signed [3:0] agg_result_fu_587_p29;
wire  signed [3:0] agg_result_fu_587_p31;

my_prj_sparsemux_33_4_11_1_0_x3 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 4'h0 ),
    .din0_WIDTH( 11 ),
    .CASE1( 4'h1 ),
    .din1_WIDTH( 11 ),
    .CASE2( 4'h2 ),
    .din2_WIDTH( 11 ),
    .CASE3( 4'h3 ),
    .din3_WIDTH( 11 ),
    .CASE4( 4'h4 ),
    .din4_WIDTH( 11 ),
    .CASE5( 4'h5 ),
    .din5_WIDTH( 11 ),
    .CASE6( 4'h6 ),
    .din6_WIDTH( 11 ),
    .CASE7( 4'h7 ),
    .din7_WIDTH( 11 ),
    .CASE8( 4'h8 ),
    .din8_WIDTH( 11 ),
    .CASE9( 4'h9 ),
    .din9_WIDTH( 11 ),
    .CASE10( 4'hA ),
    .din10_WIDTH( 11 ),
    .CASE11( 4'hB ),
    .din11_WIDTH( 11 ),
    .CASE12( 4'hC ),
    .din12_WIDTH( 11 ),
    .CASE13( 4'hD ),
    .din13_WIDTH( 11 ),
    .CASE14( 4'hE ),
    .din14_WIDTH( 11 ),
    .CASE15( 4'hF ),
    .din15_WIDTH( 11 ),
    .def_WIDTH( 11 ),
    .sel_WIDTH( 4 ),
    .dout_WIDTH( 11 ))
sparsemux_33_4_11_1_0_x3_U121(
    .din0(11'd1659),
    .din1(11'd1095),
    .din2(11'd1774),
    .din3(11'd219),
    .din4(11'd57),
    .din5(11'd1309),
    .din6(11'd1910),
    .din7(11'd715),
    .din8(11'd1669),
    .din9(11'd29),
    .din10(11'd24),
    .din11(11'd462),
    .din12(11'd1564),
    .din13(11'd56),
    .din14(11'd618),
    .din15(11'd1803),
    .def(agg_result_fu_587_p33),
    .sel(agg_result_fu_587_p34),
    .dout(agg_result_fu_587_p35)
);

always @ (posedge ap_clk) begin
    ap_ce_reg <= ap_ce;
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        and_ln105_142_reg_758 <= and_ln105_142_fu_295_p2;
        and_ln105_142_reg_758_pp0_iter2_reg <= and_ln105_142_reg_758;
        and_ln105_143_reg_771 <= and_ln105_143_fu_311_p2;
        and_ln105_144_reg_777 <= and_ln105_144_fu_321_p2;
        and_ln105_145_reg_788 <= and_ln105_145_fu_348_p2;
        and_ln105_reg_746 <= and_ln105_fu_281_p2;
        and_ln107_15_reg_765 <= and_ln107_15_fu_305_p2;
        and_ln107_15_reg_765_pp0_iter2_reg <= and_ln107_15_reg_765;
        and_ln107_15_reg_765_pp0_iter3_reg <= and_ln107_15_reg_765_pp0_iter2_reg;
        and_ln107_reg_753 <= and_ln107_fu_290_p2;
        icmp_ln4_130_reg_670 <= icmp_ln4_130_fu_192_p2;
        icmp_ln4_131_reg_676 <= icmp_ln4_131_fu_198_p2;
        icmp_ln4_132_reg_682 <= icmp_ln4_132_fu_204_p2;
        icmp_ln4_133_reg_688 <= icmp_ln4_133_fu_210_p2;
        icmp_ln4_133_reg_688_pp0_iter1_reg <= icmp_ln4_133_reg_688;
        icmp_ln4_134_reg_694 <= icmp_ln4_134_fu_216_p2;
        icmp_ln4_134_reg_694_pp0_iter1_reg <= icmp_ln4_134_reg_694;
        icmp_ln4_134_reg_694_pp0_iter2_reg <= icmp_ln4_134_reg_694_pp0_iter1_reg;
        icmp_ln4_135_reg_700 <= icmp_ln4_135_fu_222_p2;
        icmp_ln4_135_reg_700_pp0_iter1_reg <= icmp_ln4_135_reg_700;
        icmp_ln4_135_reg_700_pp0_iter2_reg <= icmp_ln4_135_reg_700_pp0_iter1_reg;
        icmp_ln4_135_reg_700_pp0_iter3_reg <= icmp_ln4_135_reg_700_pp0_iter2_reg;
        icmp_ln4_136_reg_706 <= icmp_ln4_136_fu_228_p2;
        icmp_ln4_136_reg_706_pp0_iter1_reg <= icmp_ln4_136_reg_706;
        icmp_ln4_137_reg_711 <= icmp_ln4_137_fu_234_p2;
        icmp_ln4_138_reg_716 <= icmp_ln4_138_fu_240_p2;
        icmp_ln4_138_reg_716_pp0_iter1_reg <= icmp_ln4_138_reg_716;
        icmp_ln4_139_reg_721 <= icmp_ln4_139_fu_246_p2;
        icmp_ln4_139_reg_721_pp0_iter1_reg <= icmp_ln4_139_reg_721;
        icmp_ln4_140_reg_726 <= icmp_ln4_140_fu_252_p2;
        icmp_ln4_140_reg_726_pp0_iter1_reg <= icmp_ln4_140_reg_726;
        icmp_ln4_140_reg_726_pp0_iter2_reg <= icmp_ln4_140_reg_726_pp0_iter1_reg;
        icmp_ln4_141_reg_731 <= icmp_ln4_141_fu_258_p2;
        icmp_ln4_141_reg_731_pp0_iter1_reg <= icmp_ln4_141_reg_731;
        icmp_ln4_141_reg_731_pp0_iter2_reg <= icmp_ln4_141_reg_731_pp0_iter1_reg;
        icmp_ln4_142_reg_736 <= icmp_ln4_142_fu_264_p2;
        icmp_ln4_142_reg_736_pp0_iter1_reg <= icmp_ln4_142_reg_736;
        icmp_ln4_142_reg_736_pp0_iter2_reg <= icmp_ln4_142_reg_736_pp0_iter1_reg;
        icmp_ln4_143_reg_741 <= icmp_ln4_143_fu_270_p2;
        icmp_ln4_143_reg_741_pp0_iter1_reg <= icmp_ln4_143_reg_741;
        icmp_ln4_143_reg_741_pp0_iter2_reg <= icmp_ln4_143_reg_741_pp0_iter1_reg;
        icmp_ln4_143_reg_741_pp0_iter3_reg <= icmp_ln4_143_reg_741_pp0_iter2_reg;
        icmp_ln4_reg_659 <= icmp_ln4_fu_186_p2;
        icmp_ln4_reg_659_pp0_iter1_reg <= icmp_ln4_reg_659;
        icmp_ln4_reg_659_pp0_iter2_reg <= icmp_ln4_reg_659_pp0_iter1_reg;
        or_ln120_110_reg_793 <= or_ln120_110_fu_385_p2;
        or_ln120_114_reg_804 <= or_ln120_114_fu_508_p2;
        or_ln120_reg_783 <= or_ln120_fu_337_p2;
        select_ln120_128_reg_799 <= select_ln120_128_fu_453_p3;
        select_ln120_134_reg_809 <= select_ln120_134_fu_552_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce_reg)) begin
        ap_return_int_reg <= agg_result_fu_587_p35;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce)) begin
        x_0_val_int_reg <= x_0_val;
        x_1_val_int_reg <= x_1_val;
        x_2_val_int_reg <= x_2_val;
        x_3_val_int_reg <= x_3_val;
        x_5_val_int_reg <= x_5_val;
        x_6_val_int_reg <= x_6_val;
        x_8_val_int_reg <= x_8_val;
        x_9_val_int_reg <= x_9_val;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return = ap_return_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return = agg_result_fu_587_p35;
    end else begin
        ap_return = 'bx;
    end
end

assign agg_result_fu_587_p33 = 'bx;

assign agg_result_fu_587_p34 = ((or_ln120_115_fu_575_p2[0:0] == 1'b1) ? select_ln120_134_reg_809 : 4'd15);

assign and_ln105_142_fu_295_p2 = (xor_ln107_fu_276_p2 & icmp_ln4_131_reg_676);

assign and_ln105_143_fu_311_p2 = (icmp_ln4_132_reg_682 & and_ln105_fu_281_p2);

assign and_ln105_144_fu_321_p2 = (icmp_ln4_133_reg_688 & and_ln107_fu_290_p2);

assign and_ln105_145_fu_348_p2 = (icmp_ln4_134_reg_694_pp0_iter1_reg & and_ln105_142_reg_758);

assign and_ln105_146_fu_465_p2 = (icmp_ln4_135_reg_700_pp0_iter2_reg & and_ln107_15_reg_765_pp0_iter2_reg);

assign and_ln105_147_fu_352_p2 = (icmp_ln4_136_reg_706_pp0_iter1_reg & and_ln105_143_reg_771);

assign and_ln105_148_fu_331_p2 = (and_ln105_fu_281_p2 & and_ln105_155_fu_326_p2);

assign and_ln105_149_fu_356_p2 = (icmp_ln4_138_reg_716_pp0_iter1_reg & and_ln105_144_reg_777);

assign and_ln105_150_fu_365_p2 = (and_ln107_reg_753 & and_ln105_156_fu_360_p2);

assign and_ln105_151_fu_469_p2 = (icmp_ln4_140_reg_726_pp0_iter2_reg & and_ln105_145_reg_788);

assign and_ln105_152_fu_478_p2 = (and_ln105_157_fu_473_p2 & and_ln105_142_reg_758_pp0_iter2_reg);

assign and_ln105_153_fu_483_p2 = (icmp_ln4_142_reg_736_pp0_iter2_reg & and_ln105_146_fu_465_p2);

assign and_ln105_154_fu_570_p2 = (and_ln107_15_reg_765_pp0_iter3_reg & and_ln105_158_fu_565_p2);

assign and_ln105_155_fu_326_p2 = (xor_ln107_61_fu_316_p2 & icmp_ln4_137_reg_711);

assign and_ln105_156_fu_360_p2 = (xor_ln107_62_fu_343_p2 & icmp_ln4_139_reg_721_pp0_iter1_reg);

assign and_ln105_157_fu_473_p2 = (xor_ln107_63_fu_460_p2 & icmp_ln4_141_reg_731_pp0_iter2_reg);

assign and_ln105_158_fu_565_p2 = (xor_ln107_64_fu_560_p2 & icmp_ln4_143_reg_741_pp0_iter3_reg);

assign and_ln105_fu_281_p2 = (icmp_ln4_reg_659 & icmp_ln4_130_reg_670);

assign and_ln107_15_fu_305_p2 = (xor_ln107_fu_276_p2 & xor_ln107_60_fu_300_p2);

assign and_ln107_fu_290_p2 = (xor_ln107_59_fu_285_p2 & icmp_ln4_reg_659);

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign icmp_ln4_130_fu_192_p2 = (($signed(x_2_val_int_reg) < $signed(18'd71939)) ? 1'b1 : 1'b0);

assign icmp_ln4_131_fu_198_p2 = (($signed(x_3_val_int_reg) < $signed(18'd88618)) ? 1'b1 : 1'b0);

assign icmp_ln4_132_fu_204_p2 = (($signed(x_6_val_int_reg) < $signed(18'd35968)) ? 1'b1 : 1'b0);

assign icmp_ln4_133_fu_210_p2 = (($signed(x_5_val_int_reg) < $signed(18'd3293)) ? 1'b1 : 1'b0);

assign icmp_ln4_134_fu_216_p2 = (($signed(x_0_val_int_reg) < $signed(18'd13440)) ? 1'b1 : 1'b0);

assign icmp_ln4_135_fu_222_p2 = (($signed(x_2_val_int_reg) < $signed(18'd88935)) ? 1'b1 : 1'b0);

assign icmp_ln4_136_fu_228_p2 = (($signed(x_1_val_int_reg) < $signed(18'd20096)) ? 1'b1 : 1'b0);

assign icmp_ln4_137_fu_234_p2 = (($signed(x_9_val_int_reg) < $signed(18'd261180)) ? 1'b1 : 1'b0);

assign icmp_ln4_138_fu_240_p2 = (($signed(x_8_val_int_reg) < $signed(18'd24)) ? 1'b1 : 1'b0);

assign icmp_ln4_139_fu_246_p2 = (($signed(x_9_val_int_reg) < $signed(18'd260840)) ? 1'b1 : 1'b0);

assign icmp_ln4_140_fu_252_p2 = (($signed(x_6_val_int_reg) < $signed(18'd7040)) ? 1'b1 : 1'b0);

assign icmp_ln4_141_fu_258_p2 = (($signed(x_3_val_int_reg) < $signed(18'd73590)) ? 1'b1 : 1'b0);

assign icmp_ln4_142_fu_264_p2 = (($signed(x_0_val_int_reg) < $signed(18'd10624)) ? 1'b1 : 1'b0);

assign icmp_ln4_143_fu_270_p2 = (($signed(x_3_val_int_reg) < $signed(18'd109807)) ? 1'b1 : 1'b0);

assign icmp_ln4_fu_186_p2 = (($signed(x_9_val_int_reg) < $signed(18'd261524)) ? 1'b1 : 1'b0);

assign or_ln120_106_fu_370_p2 = (and_ln105_reg_746 | and_ln105_149_fu_356_p2);

assign or_ln120_107_fu_375_p2 = (and_ln105_reg_746 | and_ln105_144_reg_777);

assign or_ln120_108_fu_379_p2 = (or_ln120_107_fu_375_p2 | and_ln105_150_fu_365_p2);

assign or_ln120_109_fu_488_p2 = (icmp_ln4_reg_659_pp0_iter2_reg | and_ln105_151_fu_469_p2);

assign or_ln120_110_fu_385_p2 = (icmp_ln4_reg_659_pp0_iter1_reg | and_ln105_145_fu_348_p2);

assign or_ln120_111_fu_493_p2 = (or_ln120_110_reg_793 | and_ln105_152_fu_478_p2);

assign or_ln120_112_fu_498_p2 = (icmp_ln4_reg_659_pp0_iter2_reg | and_ln105_142_reg_758_pp0_iter2_reg);

assign or_ln120_113_fu_502_p2 = (or_ln120_112_fu_498_p2 | and_ln105_153_fu_483_p2);

assign or_ln120_114_fu_508_p2 = (or_ln120_112_fu_498_p2 | and_ln105_146_fu_465_p2);

assign or_ln120_115_fu_575_p2 = (or_ln120_114_reg_804 | and_ln105_154_fu_570_p2);

assign or_ln120_fu_337_p2 = (and_ln105_148_fu_331_p2 | and_ln105_143_fu_311_p2);

assign select_ln120_123_fu_407_p3 = ((or_ln120_reg_783[0:0] == 1'b1) ? select_ln120_fu_400_p3 : 2'd3);

assign select_ln120_124_fu_418_p3 = ((and_ln105_reg_746[0:0] == 1'b1) ? zext_ln120_21_fu_414_p1 : 3'd4);

assign select_ln120_125_fu_425_p3 = ((or_ln120_106_fu_370_p2[0:0] == 1'b1) ? select_ln120_124_fu_418_p3 : 3'd5);

assign select_ln120_126_fu_433_p3 = ((or_ln120_107_fu_375_p2[0:0] == 1'b1) ? select_ln120_125_fu_425_p3 : 3'd6);

assign select_ln120_127_fu_441_p3 = ((or_ln120_108_fu_379_p2[0:0] == 1'b1) ? select_ln120_126_fu_433_p3 : 3'd7);

assign select_ln120_128_fu_453_p3 = ((icmp_ln4_reg_659_pp0_iter1_reg[0:0] == 1'b1) ? zext_ln120_22_fu_449_p1 : 4'd8);

assign select_ln120_129_fu_514_p3 = ((or_ln120_109_fu_488_p2[0:0] == 1'b1) ? select_ln120_128_reg_799 : 4'd9);

assign select_ln120_130_fu_521_p3 = ((or_ln120_110_reg_793[0:0] == 1'b1) ? select_ln120_129_fu_514_p3 : 4'd10);

assign select_ln120_131_fu_528_p3 = ((or_ln120_111_fu_493_p2[0:0] == 1'b1) ? select_ln120_130_fu_521_p3 : 4'd11);

assign select_ln120_132_fu_536_p3 = ((or_ln120_112_fu_498_p2[0:0] == 1'b1) ? select_ln120_131_fu_528_p3 : 4'd12);

assign select_ln120_133_fu_544_p3 = ((or_ln120_113_fu_502_p2[0:0] == 1'b1) ? select_ln120_132_fu_536_p3 : 4'd13);

assign select_ln120_134_fu_552_p3 = ((or_ln120_114_fu_508_p2[0:0] == 1'b1) ? select_ln120_133_fu_544_p3 : 4'd14);

assign select_ln120_fu_400_p3 = ((and_ln105_143_reg_771[0:0] == 1'b1) ? zext_ln120_fu_396_p1 : 2'd2);

assign xor_ln107_59_fu_285_p2 = (icmp_ln4_130_reg_670 ^ 1'd1);

assign xor_ln107_60_fu_300_p2 = (icmp_ln4_131_reg_676 ^ 1'd1);

assign xor_ln107_61_fu_316_p2 = (icmp_ln4_132_reg_682 ^ 1'd1);

assign xor_ln107_62_fu_343_p2 = (icmp_ln4_133_reg_688_pp0_iter1_reg ^ 1'd1);

assign xor_ln107_63_fu_460_p2 = (icmp_ln4_134_reg_694_pp0_iter2_reg ^ 1'd1);

assign xor_ln107_64_fu_560_p2 = (icmp_ln4_135_reg_700_pp0_iter3_reg ^ 1'd1);

assign xor_ln107_fu_276_p2 = (icmp_ln4_reg_659 ^ 1'd1);

assign xor_ln120_fu_390_p2 = (1'd1 ^ and_ln105_147_fu_352_p2);

assign zext_ln120_21_fu_414_p1 = select_ln120_123_fu_407_p3;

assign zext_ln120_22_fu_449_p1 = select_ln120_127_fu_441_p3;

assign zext_ln120_fu_396_p1 = xor_ln120_fu_390_p2;

endmodule //my_prj_decision_function_ap_fixed_18_8_5_3_0_ap_fixed_18_8_5_3_0_13
